### ISSUE TITLE
cannot search in chinese when press ctrl-T or by ios version

### ISSUE THREAD

**Issue by Meavel** [4very/awesome-arc#2]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add \_\_\_\_" as Title**
[ ] Done

**Provide a link to the proposed addition.**
Place link here.

**What section or subsection should the item be placed under.**
As a Chinese user, I cannot search in Chinese. It was under ios and windows (both 10 and 11).
For ios version, when I want to search in Chinese, sometimes it won't have the search result.
For windows version, when I press ctrl-T, and type in Chinese, I will get the wrong result.
So, nowadays, after press ctrl-T, I have to type google.com, and then, I search Chinese articles in google's search box.
for example, 

**Explain why it should be added**
A Chinese character support for searching.

**Additional context**

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [ ] I have checked for other similar issues
- [ ] I have explained why this change is important
- [ ] I have added necessary documentation (if appropriate)
![image](https://github.com/4very/awesome-arc/assets/80664602/029de4d9-a780-4023-a6ef-d39c2bfd2c28)

**Comment by 4very** [comment]
Hello! Unfortunately this repo is meant as a collection of resources to use with the Arc Browser. I am in no way affiliated with Arc or BCNY. You can report your bug at https://resources.arc.net/hc/en-us/requests/new or the r/arcbrowser discord server at https://discord.gg/arcinternet could be of some help.
