### ISSUE TITLE
When will a version for Linux or Ubuntu be released?

### ISSUE THREAD

**Issue by lucenarenato** [4very/awesome-arc#3]
When will a version for Linux or Ubuntu be released?

**Comment by 4very** [comment]
Hello! Unfortunately this repo is meant as a collection of resources to use with the Arc Browser. I am in no way affiliated with Arc or BCNY. You can report your bug or request features at https://resources.arc.net/hc/en-us/requests/new or the r/arcbrowser discord server at https://discord.gg/arcinternet could be of some help.
